"use client"
import { QueryClient, QueryClientProvider } from 'react-query';
import '../(App-wrapper)/globals.css'
// export const metadata = {
//   title: 'Admin Dashboard',
//   description: 'Generated by Next.js',
// }

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
