"use client"
import { QueryClient, QueryClientProvider } from 'react-query';
import '../(App-wrapper)/globals.css'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// export const metadata = {
//   title: 'Admin Dashboard',
//   description: 'Generated by Next.js',
// }

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
